config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy" 
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(index create destroy)
  end 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".desc_a" %> 
    <%= link_to t("ruby_on_rails_tut"), Settings.links.rails_tutorial.home_page %>
    <%= t ".desc_b" %>
    <%= link_to t("ruby_on_rails_tut_author"), Settings.links.rails_tutorial.author %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about_footer"), about_path %></li>
      <li><%= link_to t(".contact_footer"), contact_path %></li></li>
      <li><%= link_to t(".new_footer"), Settings.links.rails_tutorial.news %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home_header"), root_path %></li>
        <li><%= link_to t(".help_header"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users_header"), users_path %><li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", data: { "toggle" => "dropdown"}} do %>
              <%= t ".account_header" %> 
              <b class="caret"></b>
            <% end %>

            <ul class="dropdown-menu">
              <li><%= link_to t(".profile_header"), current_user %></li>
              <li><%= link_to t(".setting_header"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
              <%= link_to t(".logout_header"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login_header"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t ".title" %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>